logging.level:
    root: "warn"
    org.springframework.web: "info"
    # org.atmosphere: "warn"

vaadin:
    # Launch the default browser when starting the application in development mode
    launch-browser: false
    # To improve the performance during development.
    # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
    allowed-packages: "com.vaadin,org.vaadin,dev.hilla,com.example.application"

spring:
    mustache:
        check-template-location: false
    jpa:
        # Disable warnings
        open-in-view: true
        defer-datasource-initialization: true

server.port: "${PORT:8080}"
