logging.level:
    root: "warn"
    # org.atmosphere: "warn"
    org.springframework.web: "info"
    com.vaadin.flow.server.communication.ReturnChannelHandler: "error"       # Disable warnings
    org.springframework.beans.factory.support.DisposableBeanAdapter: "error" # Disable warnings

vaadin:
    # Launch the default browser when starting the application in development mode
    launch-browser: false
    # To improve the performance during development.
    # For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
    allowed-packages: "com.vaadin,org.vaadin,dev.hilla,com.example.application"

    pushMode: "disabled" # Disable warnings

spring:
    mustache:
        check-template-location: false
    jpa:
        open-in-view: false # Disable warnings
        defer-datasource-initialization: true
    # datasource:
    #     url: "jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE"

server.port: "${PORT:8080}"
